In [2]:
import pandas as pd

df = pd.read_csv("data/sales.csv")

df.head(2)

         Date  Day     Month  Year  ...  Unit_Price Profit Cost Revenue
0  2013-11-26   26  November  2013  ...         120    590  360     950
1  2015-11-26   26  November  2015  ...         120    590  360     950

[2 rows x 18 columns]

In [3]:
df.describe()

                 Day           Year  ...           Cost        Revenue
count  113036.000000  113036.000000  ...  113036.000000  113036.000000
mean       15.665753    2014.401739  ...     469.318695     754.370360
std         8.781567       1.272510  ...     884.866118    1309.094674
min         1.000000    2011.000000  ...       1.000000       2.000000
25%         8.000000    2013.000000  ...      28.000000      63.000000
50%        16.000000    2014.000000  ...     108.000000     223.000000
75%        23.000000    2016.000000  ...     432.000000     800.000000
max        31.000000    2016.000000  ...   42978.000000   58074.000000

[8 rows x 9 columns]

In [7]:
df.describe().T.drop(["count"], axis=1).drop(["Day", "Year"])

                      mean          std   min   25%    50%    75%      max
Customer_Age     35.919212    11.021936  17.0  28.0   35.0   43.0     87.0
Order_Quantity   11.901660     9.561857   1.0   2.0   10.0   20.0     32.0
Unit_Cost       267.296366   549.835483   1.0   2.0    9.0   42.0   2171.0
Unit_Price      452.938427   922.071219   2.0   5.0   24.0   70.0   3578.0
Profit          285.051665   453.887443 -30.0  29.0  101.0  358.0  15096.0
Cost            469.318695   884.866118   1.0  28.0  108.0  432.0  42978.0
Revenue         754.370360  1309.094674   2.0  63.0  223.0  800.0  58074.0

## Filter out a country and fins its KPIs

In [21]:
country = "CanaDA"
df_by_country = df.query("Country.str.casefold() == @country.casefold()")
df_by_country.head(2)

         Date  Day     Month  Year  ...  Unit_Price Profit Cost Revenue
0  2013-11-26   26  November  2013  ...         120    590  360     950
1  2015-11-26   26  November  2015  ...         120    590  360     950

[2 rows x 18 columns]

In [19]:
str(df_by_country["Profit"].sum()), str(df_by_country["Cost"].sum()), str(len(df_by_country))

('3717296', '4218442', '14178')

make in to dict

In [ ]:
{"total_profit": str(df_by_country["Profit"].sum()),
"total_cost": str(df_by_country["Cost"].sum()),
"number_of_purchases": str(len(df_by_country)
}